apiVersion: v1
kind: Secret
metadata:
  name: mysecrets
type: Opaque
stringData:
  sqluser: dbuser
  sqlpassword: passwd
  influxdbuser: admin
  influxdbpassword: passwd
  sshuser: admin
  sshpassword: passwd
  ftpsuser: admin
  ftpspassword: passwd
  clusterip: 172.17.0.2
